version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./instance:/app/instance
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development  # Change to production in real deployment
      - SECRET_KEY=your-secret-key-change-this
    restart: unless-stopped